# Generated by Django 2.2.16 on 2022-12-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221216_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Укажите группу, к которой будет относится пост', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
